#Jekyll config file

# Setup
name: Grant Surlyn
author: Grant Surlyn
title: Sinistrocular
url: http://sinistrocular.com
static_url: https://static.sinistrocular.com
github_url: https://github.com/sunflowerseastar/sinistrocular/blob/master
baseurl: ""

exclude:
  - README.md
  - __reference
  - node_modules
  - bower_components
  - source

collections:
  - categories

# Syntax highlighting
#highlighter:         pygments

# Permalinks
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: pretty
#relative_permalinks: true

github_username: sunflowerseastar

# Build settings
markdown: kramdown

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          styles
  style:            :compressed
